apiVersion: v1
kind: ReplicationController 
metadata: 
  name: myweb-mysql   
spec: 
  replicas: 1 
  selector: 
    app: myweb-mysql 
  template: 
    metadata: 
      labels: 
        app: myweb-mysql 
    spec: 
      containers: 
        - image: docker.io/mysql
          name: myweb-mysql 
          ports: 
            - containerPort: 3306 
          env: 
            - name: MYSQL_ROOT_PASSWORD 
              value: 123456 
          volumeMounts: 
            - name: master
              mountPath: /var/lib/mysql 
          volumes: 
            - name: master
              hostPath: 
                path: /root/mysql/mysql/data
