apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql-slave
spec:
  capacity:
    storage: 6Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /root/k8s_wf/mysql/Storage/mysql_pv/mysql_slave
    server: 121.195.169.157
  persistentVolumeReclaimPolicy: Recycle 
